services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        container_name: php
        volumes:
            - .:/var/www/html
        depends_on:
            - database
    web:
        build:
            context: .
            dockerfile: Dockerfile.apache
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
    database:
        image: mysql:8.0
        container_name: database
        volumes:
            - ./server_data:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=app"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=app@"
            - "MYSQL_ROOT_PASSWORD=root@"
        ports:
            - "3306:3306"
        command:
            [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--default-authentication-plugin=mysql_native_password",
            ]
