# Use the official Apache image
FROM httpd:2.4.52-alpine

# Copy Apache virtual host configuration
COPY server_conf/apache.conf /usr/local/apache2/conf/httpd.conf

# RUN echo "ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/var/www/html/$1" >> /usr/local/apache2/conf/httpd.conf

# Expose port 80
EXPOSE 80
